[package]
name = "binance-sdk-rs"
version = "0.2.4"
license = "MIT"
authors = ["anlithov <anlithov@gmail.com>"]
edition = "2021"
description = "Rust Async SDK for the Binance"
keywords = ["crypto", "trading", "binance"]
repository = "https://github.com/anlithov/binance-api-rs"
readme = "README.md"

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
hmac = "0.13.0-pre.4"
sha2 = "0.11.0-pre.4"
hex = "0.4.3"
anyhow = '1.0.95'

[dev-dependencies]
tokio = { version = "1.43.0", features = ['macros', 'rt-multi-thread'] }
dotenvy = "0.15.7"